Update build.yml

diff --git a/.github/workflows/build.yml b/.github/workflows/build.yml
--- a/.github/workflows/build.yml
+++ b/.github/workflows/build.yml
@@ -131,15 +131,15 @@ jobs:
             pip install -r "${{ needs.generate-matrix.outputs.project_tools_path }}/requirements.txt"
           fi
 
-      - name: Prepare CI workspace (setup_ci.sh)
-        shell: bash
-        run: |
-          set -e
-          SCRIPT_PATH="${{ needs.generate-matrix.outputs.project_tools_path }}/setup_ci.sh"
-          chmod +x "$SCRIPT_PATH"
-          "$SCRIPT_PATH" --project-path "${{ env.ESP32_PROJECT_PATH }}" "${{ env.BUILD_PATH }}"
-          test -d "${{ env.BUILD_PATH }}" || { \
-            echo "Missing build dir"; exit 1; }
+      #- name: Prepare CI workspace (setup_ci.sh)
+        #shell: bash
+        #run: |
+          #set -e
+          #SCRIPT_PATH="${{ needs.generate-matrix.outputs.project_tools_path }}/setup_ci.sh"
+          #chmod +x "$SCRIPT_PATH"
+        #  "$SCRIPT_PATH" --project-path "${{ env.ESP32_PROJECT_PATH }}" "${{ env.BUILD_PATH }}"
+          #test -d "${{ env.BUILD_PATH }}" || { \
+            #echo "Missing build dir"; exit 1; }
 
       - name: Cache ccache
         if: ${{ !inputs.clean_build }}
